name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1']
    name: PHP ${{ matrix.php }}
    env:
      PHP_VERSION: ${{ matrix.php }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath,gmp,intl
        env:
          runner: ubuntu-18.04

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install composer packages
        run: composer install --prefer-dist --no-interaction

      - name: Configure Laravel
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Tests Coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: PHP_VERSION
          fail_ci_if_error: true